# Generated by Django 3.2.5 on 2021-10-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_sub',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
