# Generated by Django 3.2.5 on 2021-08-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('B', 'پرفروش'), ('N', 'جدید'), ('Un', 'ناموجود')], max_length=2),
        ),
    ]
