# Generated by Django 3.2.5 on 2021-08-23 08:31

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210823_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(allow_unicode=True, blank=True, default='', editable=False, populate_from=['name'], unique=True),
            preserve_default=False,
        ),
    ]
