# Generated by Django 3.2.5 on 2021-08-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20210823_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('B', 'پرفروش'), ('N', 'جدید'), ('Un', 'ناموجود'), ('O', 'اصالت کالا')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='number_sold',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
