# Generated by Django 3.2.5 on 2021-09-26 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'کاربر کلی', 'verbose_name_plural': 'کاربران کلی'},
        ),
    ]
