# Generated by Django 3.2.5 on 2021-08-27 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20210822_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='number_used',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
            preserve_default=False,
        ),
    ]
