# Generated by Django 3.2.5 on 2021-09-26 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('start_date',), 'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارش ها'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('ordered_date',), 'verbose_name': 'سفارش-محصول', 'verbose_name_plural': 'سفارش-محصول ها'},
        ),
    ]
